// This code was generated by a tool: InfrastructureTemplates\EntityEditUriTemplate.tt
namespace Admin.LocationModule.Uris
{
    using System;

    using Admin.LocationModule.Views;

    using Common;

    public class LocationEditUri : Uri
    {
        public LocationEditUri(int locationId, DateTime validAt)
            : base(
                LocationViewNames.LocationEditView
                + string.Format(
                    "?{0}={1}&{2}={3}", 
                    NavigationParameters.EntityId, 
                    locationId, 
                    NavigationParameters.ValidAtDate, 
                    validAt), 
                UriKind.Relative)
        {
        }
    }
}