// This code was generated by a tool: ViewTemplates\EntitySearchResultsViewCodeTemplate.tt
namespace Admin.PartyModule.Views
{
    using System.Windows.Controls;

    using Admin.PartyModule.ViewModels;

    /// <summary>
    /// Interaction logic for PartySearchResultsView.xaml
    /// </summary>
    public partial class PartySearchResultsView : UserControl
    {
        public PartySearchResultsView(PartySearchResultsViewModel partySearchResultsViewModel)
        {
            this.DataContext = partySearchResultsViewModel;
            this.InitializeComponent();
        }
    }
}