// This code was generated by a tool: ViewTemplates\EntityEmbeddedSearchResultsViewCodeTemplate.tt
namespace Admin.PartyModule.Views
{
    using System.Windows.Controls;

    using Admin.PartyModule.ViewModels;

    /// <summary>
    /// Interaction logic for PartyEmbeddedSearchResultsView.xaml
    /// </summary>
    public partial class PartyEmbeddedSearchResultsView : UserControl
    {
        public PartyEmbeddedSearchResultsView(PartyEmbeddedSearchResultsViewModel partyEmbeddedSearchResultsViewModel)
        {
            this.DataContext = partyEmbeddedSearchResultsViewModel;
            this.InitializeComponent();
        }
    }
}