// This code was generated by a tool: ViewTemplates\EntityEmbeddedSearchResultsViewCodeTemplate.tt
namespace Admin.PartyRoleModule.Views
{
    using System.Windows.Controls;
    using Admin.PartyRoleModule.ViewModels;

    /// <summary>
    /// Interaction logic for PartyRoleEmbeddedSearchResultsView.xaml
    /// </summary>
    public partial class PartyRoleEmbeddedSearchResultsView : UserControl
    {
        public PartyRoleEmbeddedSearchResultsView(PartyRoleEmbeddedSearchResultsViewModel partyroleEmbeddedSearchResultsViewModel)
        {
            this.DataContext = partyroleEmbeddedSearchResultsViewModel;
            this.InitializeComponent();
        }
    }
}
