// This code was generated by a tool: InfrastructureTemplates\EntityViewNamesTemplate.tt
namespace Admin.PartyRoleModule.Views
{
    public static class PartyRoleViewNames
    {
        public static string PartyRoleEditView = "PartyRoleEditView";
        public static string PartyRoleAddView = "PartyRoleAddView";
        public static string PartyRoleSearchResultsView = "PartyRole";
        public static string PartyRoleEmbeddedSearchResultsView = "PartyRoleEmbeddedSearchResultsView";
        }
}
    