// This code was generated by a tool: InfrastructureTemplates\ModuleInitTemplate.tt
namespace Admin.PersonModule
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using Admin.PersonModule.ViewModels;
    using Admin.PersonModule.Views;

    using Common.Services;

    using EnergyTrading.Mdm.Client.Services;
    using EnergyTrading.Mdm.Client.WebClient;
    using EnergyTrading.Mdm.Contracts;
    using EnergyTrading.MDM.Contracts.Sample;

    using Microsoft.Practices.Prism.Events;
    using Microsoft.Practices.Prism.Modularity;
    using Microsoft.Practices.Unity;

    public class ModuleInit : IModule
    {
        private readonly IUnityContainer container;

        private readonly IApplicationMenuRegistry menuRegistry;

        public ModuleInit(IUnityContainer container, IApplicationMenuRegistry menuRegistry)
        {
            this.container = container;
            this.menuRegistry = menuRegistry;
        }

        public void Initialize()
        {
            this.Register();
            this.PopulateReferenceData();

            this.menuRegistry.RegisterMenuItem(
                "Person", 
                string.Empty, 
                typeof(PersonSearchResultsView), 
                new Uri(PersonViewNames.PersonAddView, UriKind.Relative), 
                "LastName", 
                "Sur_name");
            this.menuRegistry.RegisterEntitySelector("Person", typeof(PersonSelectorView));
        }

        private void PopulateReferenceData()
        {
            ReferenceDataList message = null;
            message =
                this.container.Resolve<IMessageRequester>()
                    .Request<ReferenceDataList>(Server.Name + "ReferenceData/list/PersonRole")
                    .Message;
            IList<string> role = message != null
                                     ? message.Select(data => data.Value).OrderBy(s => s).ToList()
                                     : new List<string>();

            this.container.RegisterInstance("roles", role, new ContainerControlledLifetimeManager());
        }

        private void Register()
        {
            this.container.RegisterType<IMdmEntityService<Person>, MdmEntityService<Person>>(
                new ContainerControlledLifetimeManager(), 
                new InjectionConstructor(Server.Name + "person", new ResolvedParameter<IMessageRequester>()));
            this.container.RegisterType<object, PersonEditView>(PersonViewNames.PersonEditView);
            this.container.RegisterType<object, PersonAddView>(PersonViewNames.PersonAddView);
            this.container.RegisterType<object, PersonSearchResultsView>(PersonViewNames.PersonSearchResultsView);
            this.container.RegisterType<object, PersonEmbeddedSearchResultsView>(
                PersonViewNames.PersonEmbeddedSearchResultsView, 
                new ContainerControlledLifetimeManager());

            this.container.RegisterType<PersonAddViewModel>(
                new ContainerControlledLifetimeManager(), 
                new InjectionConstructor(
                    new ResolvedParameter<IEventAggregator>(), 
                    new ResolvedParameter<IMdmService>(), 
                    new ResolvedParameter<IList<string>>("roles")));

            this.container.RegisterType<PersonEditViewModel>(
                new ContainerControlledLifetimeManager(), 
                new InjectionConstructor(
                    new ResolvedParameter<IEventAggregator>(), 
                    new ResolvedParameter<IMdmService>(), 
                    new ResolvedParameter<INavigationService>(), 
                    new ResolvedParameter<IMappingService>(), 
                    new ResolvedParameter<IApplicationCommands>(), 
                    new ResolvedParameter<IList<string>>("roles")));

            this.container.RegisterType<PersonSelectorView>();
            this.container.RegisterType<PersonSelectorViewModel>();

            this.container.RegisterInstance<Func<int, IMdmEntity>>(
                "Person", 
                entityId =>
                    {
                        var entityService = container.Resolve<IMdmEntityService<Person>>();
                        var response = entityService.Get(entityId);
                        return response.Message;
                    });
        }
    }
}