// This code was generated by a tool: InfrastructureTemplates\ModuleInitTemplate.tt
namespace Admin.SourceSystemModule
{
    using System;

    using Admin.SourceSystemModule.ViewModels;
    using Admin.SourceSystemModule.Views;

    using Common.Services;

    using EnergyTrading.Mdm.Client.Services;
    using EnergyTrading.Mdm.Client.WebClient;
    using EnergyTrading.Mdm.Contracts;

    using Microsoft.Practices.Prism.Events;
    using Microsoft.Practices.Prism.Modularity;
    using Microsoft.Practices.Unity;

    public class ModuleInit : IModule
    {
        private readonly IUnityContainer container;
        private readonly IApplicationMenuRegistry menuRegistry;

        public ModuleInit(IUnityContainer container, IApplicationMenuRegistry menuRegistry)
        {
            this.container = container;
            this.menuRegistry = menuRegistry;
        }

        public void Initialize()
        {
            this.Register();
            this.PopulateReferenceData();

            this.menuRegistry.RegisterMenuItem("SourceSystem", string.Empty, typeof(SourceSystemSearchResultsView), new Uri(SourceSystemViewNames.SourceSystemAddView, UriKind.Relative), "Name", "_Name");
            this.menuRegistry.RegisterEntitySelector("SourceSystem", typeof(SourceSystemSelectorView));
        }

        private void Register()
        {
            this.container.RegisterType<IMdmEntityService<SourceSystem>, MdmEntityService<SourceSystem>>(
                new ContainerControlledLifetimeManager(),
                new InjectionConstructor(Server.Name + "sourcesystem", new ResolvedParameter<IMessageRequester>()));
            this.container.RegisterType<object, SourceSystemEditView>(SourceSystemViewNames.SourceSystemEditView);
            this.container.RegisterType<object, SourceSystemAddView>(SourceSystemViewNames.SourceSystemAddView);
            this.container.RegisterType<object, SourceSystemSearchResultsView>(SourceSystemViewNames.SourceSystemSearchResultsView);
            this.container.RegisterType<object, SourceSystemEmbeddedSearchResultsView>(SourceSystemViewNames.SourceSystemEmbeddedSearchResultsView, new ContainerControlledLifetimeManager());
                this.container.RegisterType<object, SourceSystemEditCloneView>(SourceSystemViewNames.SourceSystemEditCloneView);
            this.container.RegisterType<object, SourceSystemAddCloneView>(SourceSystemViewNames.SourceSystemAddCloneView);
                    
            this.container.RegisterType<SourceSystemAddViewModel>(
                new ContainerControlledLifetimeManager(),
                new InjectionConstructor(
                new ResolvedParameter<IEventAggregator>(),
                new ResolvedParameter<IMdmService>()));

            this.container.RegisterType<SourceSystemEditViewModel>(
                new ContainerControlledLifetimeManager(),
                new InjectionConstructor(
                new ResolvedParameter<IEventAggregator>(),
                new ResolvedParameter<IMdmService>(),
                new ResolvedParameter<INavigationService>(),
                new ResolvedParameter<IMappingService>(),
                new ResolvedParameter<IApplicationCommands>()));

                        this.container.RegisterType<SourceSystemAddCloneViewModel>(
                    new ContainerControlledLifetimeManager(),
                    new InjectionConstructor(
                    new ResolvedParameter<IEventAggregator>(),
                    new ResolvedParameter<IMdmService>(),
                    new ResolvedParameter<INavigationService>()
                                  ));

                this.container.RegisterType<SourceSystemEditCloneViewModel>(
                    new ContainerControlledLifetimeManager(),
                    new InjectionConstructor(
                    new ResolvedParameter<IEventAggregator>(),
                    new ResolvedParameter<IMdmService>(),
                    new ResolvedParameter<INavigationService>(),
                    new ResolvedParameter<IMappingService>(),
                    new ResolvedParameter<IApplicationCommands>()
                                  ));

                    
            this.container.RegisterType<SourceSystemSelectorView>();
            this.container.RegisterType<SourceSystemSelectorViewModel>();
			
            this.container.RegisterInstance<Func<int, IMdmEntity>>("SourceSystem",
                (entityId) =>
                    {
                        var entityService = container.Resolve<IMdmEntityService<SourceSystem>>();
                        var response = entityService.Get(entityId);
                        return response.Message;
                    });
        }

        private void PopulateReferenceData()
        {
                }
    }
}
