// This code was generated by a tool: ViewModelTemplates\EntityEmbeddedSearchResultsViewModelTemplate.tt

using Common;
using Microsoft.Practices.Prism.Regions;

namespace Admin.BrokerModule.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Windows.Input;
    using Admin.BrokerModule.Uris;
    using Admin.BrokerModule.Views;
    using Common.Events;
    using Common.Extensions;
    using Common.Services;
    using Microsoft.Practices.Prism;
    using Microsoft.Practices.Prism.Events;
    using Microsoft.Practices.Prism.ViewModel;
    using EnergyTrading.Contracts.Search;
    using EnergyTrading.Mdm.Client.Services;
    using EnergyTrading.MDM.Contracts.Sample; using EnergyTrading.Mdm.Contracts;
    using EnergyTrading.Search;

    public class BrokerEmbeddedSearchResultsViewModel : NotificationObject, IActiveAware
    {
        private readonly IMdmService entityService;
        private readonly IRegionManager regionManager;
        private readonly IEventAggregator eventAggregator;
        private readonly INavigationService navigationService;
        private bool isActive;

        private ObservableCollection<BrokerViewModel> brokers;

        private Search search;
        private BrokerViewModel selectedBroker;

        public BrokerEmbeddedSearchResultsViewModel(
            INavigationService navigationService, 
            IEventAggregator eventAggregator, 
            IMdmService entityService, 
            IRegionManager regionManager)
        {
            this.navigationService = navigationService;
            this.eventAggregator = eventAggregator;
            this.entityService = entityService;
            this.regionManager = regionManager;
            this.IsActiveChanged += this.OnIsActiveChanged;
        }

        public event EventHandler IsActiveChanged;

        public bool IsActive
        {
            get
            {
                return this.isActive;
            }

            set
            {
                if (this.isActive != value)
                {
                    this.isActive = value;
                }

                this.IsActiveChanged(this, EventArgs.Empty);
            }
        }

        public ObservableCollection<BrokerViewModel> Brokers
        {
            get
            {
                return this.brokers;
            }

            set
            {
                this.brokers = value;
                this.RaisePropertyChanged(() => this.Brokers);
                if (Brokers != null && Brokers.Count > 0 && SelectedBroker == null) 
                    SelectedBroker = Brokers[0];
            }
        }

        public BrokerViewModel SelectedBroker
        {
            get
            {
                return this.selectedBroker;
            }

            set
            {
                this.selectedBroker = value;
                this.RaisePropertyChanged(() => this.SelectedBroker);
            }
        }
        
        public void NavigateToDetail(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Enter && this.SelectedBroker != null)
            {
                this.navigationService.NavigateMain(new BrokerEditUri(this.SelectedBroker.Id.Value, this.search.AsOf.Value));
            }
        }

        public void NavigateToDetailDoubleClick()
        {
            if (this.SelectedBroker != null)
            {
                this.navigationService.NavigateMain(new BrokerEditUri(this.SelectedBroker.Id.Value, this.search.AsOf.Value));
            }
        }

        public void Sorting()
        {
            this.SelectedBroker = null;
        }

        private void OnIsActiveChanged(object sender, EventArgs eventArgs)
        {
            if (this.isActive)
            {
                Search search = SearchBuilder.CreateSearch();

                var context =
                    MyRegion(this.regionManager.Regions).Context as
                    Tuple<int, DateTime?, string>;
                search.AsOf = context.Item2;

                string field;
                switch (context.Item3)
                {
                    case "Broker":
                        field = "Parent.Id";
                        break;
                                    case "Party":
                        field = "PartyRole.Party.Id";
                        break;
                                    default:
                        field = context.Item3 + ".Id";
                        break;
                }
                
                if (field.Contains("|"))
                {
                    search.SearchFields.Combinator = SearchCombinator.Or;
                    var fields = field.Split(new Char[]{'|'});
                    
                    foreach (string f in fields)
                    {
                        search.AddSearchCriteria(SearchCombinator.And).AddCriteria(
                            f, SearchCondition.NumericEquals, context.Item1.ToString());
                    }
                }
                else
                {
                    search.AddSearchCriteria(SearchCombinator.And).AddCriteria(
                        field, SearchCondition.NumericEquals, context.Item1.ToString());
                }

                this.entityService.ExecuteAsyncSearch<Broker>(
                    this.search = search,
                    (response) =>
                        {
                            IList<Broker> searchResults = response;
                            this.Brokers =
                                new ObservableCollection<BrokerViewModel>(
                                    searchResults.Select(
                                        x =>
                                        new BrokerViewModel(
                                            new EntityWithETag<Broker>(x, null), this.eventAggregator)).
                                        OrderBy(y => y.Name));
                        },
                    this.eventAggregator, false);
                return;
            }

            this.Brokers = new ObservableCollection<BrokerViewModel>();
        }

        IRegion MyRegion(IRegionCollection regions)
        {
            for (int i = regions.Count() - 1; i >= 0; i--)
            {
                if (regions.ElementAt(i).Name.EndsWith("-BrokerSearchResultsRegion") && regions.ElementAt(i).Context != null)
                {
                    return regions.ElementAt(i);
                }
            }

            return null;
        }
    }
}
