// <autogenerated>
//   This file was generated by T4 code generator CreateIntegrationTestsScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace MDM.Client.Sample.IntegrationTests.Location.MdmService
{
    using System.Configuration;
    using System.Net;

    using EnergyTrading.Mdm.Contracts;
    using EnergyTrading.MDM.Contracts.Sample;

    using NUnit.Framework;

    [TestFixture]
    public class MdmServiceEntityUpdateIntegrationTests : MdmServiceIntegrationTestBase
    {
        private Location location;

        protected override void OnSetup()
        {
			ConfigurationManager.AppSettings["MdmCaching"] = false.ToString();

            base.OnSetup();

            this.location = LocationData.PostBasicEntity();
        }
	
        [Test]
        public void ShouldSucceedUpdateWhenETagMatches()
        {
            // given
            var id = int.Parse(this.location.ToMdmId().Identifier);

            // when
            var response = this.MdmService.Get<Location>(id);
            var entity = response.Message;
            entity.Identifiers = new MdmIdList() {entity.Identifiers.SystemId()};

            // then
            response = this.MdmService.Update(id, entity, response.Tag);
            Assert.IsTrue(response.IsValid, "###Error : " + response.Code + " : " + (response.Fault == null ? string.Empty : response.Fault.Message + " : " + response.Fault.Reason));
        }

        [Test]
        public void ShouldFailUpdateWhenETagDiffers()
        {
            // given
            var id = int.Parse(this.location.ToMdmId().Identifier);

            // when
            var response = this.MdmService.Get<Location>(id);

            // then
            response = this.MdmService.Update(id, response.Message, "\"999888777666555\"");
            Assert.IsFalse(response.IsValid);
            Assert.AreEqual(HttpStatusCode.PreconditionFailed, response.Code);
            Assert.AreEqual("Exception of type 'EnergyTrading.MDM.Services.VersionConflictException' was thrown.", response.Fault.Message);
        }
    }
}
