// This code was generated by a tool: ViewTemplates\EntityAddCloneViewCodeTemplate.tt
namespace Admin.SourceSystemModule.Views
{
    using System.Windows.Controls;

    using Admin.SourceSystemModule.ViewModels;

    /// <summary>
    /// Interaction logic for SourceSystemAddView.xaml
    /// </summary>
    public partial class SourceSystemAddCloneView : UserControl
    {
        public SourceSystemAddCloneView(SourceSystemAddCloneViewModel sourcesystemAddCloneViewModel)
        {
            this.DataContext = sourcesystemAddCloneViewModel;
            this.InitializeComponent();
        }
    }
}