// This code was generated by a tool: InfrastructureTemplates\EntityViewNamesTemplate.tt
namespace Admin.PartyAccountabilityModule.Views
{
    public static class PartyAccountabilityViewNames
    {
        public static string PartyAccountabilityEditView = "PartyAccountabilityEditView";
        public static string PartyAccountabilityAddView = "PartyAccountabilityAddView";
        public static string PartyAccountabilitySearchResultsView = "PartyAccountability";
        public static string PartyAccountabilityEmbeddedSearchResultsView = "PartyAccountabilityEmbeddedSearchResultsView";
        }
}
    