// This code was generated by a tool: ViewTemplates\EntityEditViewCodeTemplate.tt
namespace Admin.SourceSystemModule.Views
{
    using System.Windows.Controls;

    using Admin.SourceSystemModule.ViewModels;

    /// <summary>
    /// Interaction logic for SourceSystemEditView.xaml
    /// </summary>
    public partial class SourceSystemEditView : UserControl
    {
        public SourceSystemEditView(SourceSystemEditViewModel sourcesystemEditViewModel)
        {
            this.DataContext = sourcesystemEditViewModel;
            this.InitializeComponent();
        }
    }
}