// This code was generated by a tool: ViewTemplates\EntityEmbeddedSearchResultsViewCodeTemplate.tt
namespace Admin.SourceSystemModule.Views
{
    using System.Windows.Controls;
    using Admin.SourceSystemModule.ViewModels;

    /// <summary>
    /// Interaction logic for SourceSystemEmbeddedSearchResultsView.xaml
    /// </summary>
    public partial class SourceSystemEmbeddedSearchResultsView : UserControl
    {
        public SourceSystemEmbeddedSearchResultsView(SourceSystemEmbeddedSearchResultsViewModel sourcesystemEmbeddedSearchResultsViewModel)
        {
            this.DataContext = sourcesystemEmbeddedSearchResultsViewModel;
            this.InitializeComponent();
        }
    }
}
