// This code was generated by a tool: InfrastructureTemplates\EntityEditUriTemplate.tt
namespace Admin.PartyAccountabilityModule.Uris
{
    using System;
    using Admin.PartyAccountabilityModule.Views;
    using Common;

    public class PartyAccountabilityEditUri : Uri
    {
        public PartyAccountabilityEditUri(int partyaccountabilityId, DateTime validAt) : 
            base(PartyAccountabilityViewNames.PartyAccountabilityEditView + string.Format("?{0}={1}&{2}={3}", NavigationParameters.EntityId, partyaccountabilityId, NavigationParameters.ValidAtDate, validAt), UriKind.Relative)
        {
        }
    }
}
    