// This code was generated by a tool: ViewTemplates\EntitySelectorViewCodeTemplate.tt

using System.Windows;
using System.Windows.Input;

namespace Admin.PartyModule.Views
{
    using System.Windows.Controls;
    using Admin.PartyModule.ViewModels;

    /// <summary>
    /// Interaction logic for PartySelectorView.xaml
    /// </summary>
    public partial class PartySelectorView : UserControl
    {
        public PartySelectorView(PartySelectorViewModel partySelectorViewModel)
        {
            this.DataContext = partySelectorViewModel;
            this.InitializeComponent();
            this.Loaded += OnLoaded;
        }

        public void SelectPartyMDC(object sender, MouseButtonEventArgs e)
        {
            ((PartySelectorViewModel)DataContext).SelectParty();
        }

        private void OnLoaded(object sender, RoutedEventArgs e)
        {
            Keyboard.Focus(SearchCriteriaTextBox);
        }
    }
}
