// This code was generated by a tool: ViewTemplates\EntityAddViewCodeTemplate.tt
namespace Admin.PartyModule.Views
{
    using System.Windows.Controls;
    using Admin.PartyModule.ViewModels;

    /// <summary>
    /// Interaction logic for PartyAddView.xaml
    /// </summary>
    public partial class PartyAddView : UserControl
    {
        public PartyAddView(PartyAddViewModel partyAddViewModel)
        {
            this.DataContext = partyAddViewModel;
            this.InitializeComponent();
        }
    }
}
