// This code was generated by a tool: ViewTemplates\EntityEditViewCodeTemplate.tt
namespace Admin.PartyModule.Views
{
    using System.Windows.Controls;

    using Admin.PartyModule.ViewModels;

    /// <summary>
    /// Interaction logic for PartyEditView.xaml
    /// </summary>
    public partial class PartyEditView : UserControl
    {
        public PartyEditView(PartyEditViewModel partyEditViewModel)
        {
            this.DataContext = partyEditViewModel;
            this.InitializeComponent();
        }
    }
}