// <autogenerated>
//   This file was generated by T4 code generator CreateIntegrationTestsScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace MDM.Client.Sample.IntegrationTests.Broker
{
    using EnergyTrading.Mdm.Client.Services;
    using EnergyTrading.Mdm.Contracts;
    using EnergyTrading.MDM.Contracts.Sample;

    using MDM.Client.Sample.IntegrationTests.Party;

    using Microsoft.Practices.ServiceLocation;

    using NUnit.Framework;

    public class BrokerData
    {
        public static Broker PostBasicEntity()
        {
            var mdmService = ServiceLocator.Current.GetInstance<IMdmEntityService<Broker>>();

            var entity = ObjectMother.Create<Broker>();
            var mappings = entity.Identifiers;
            entity.Identifiers = new MdmIdList();
            SetAdditionalData(entity);
            var response = mdmService.Create(entity);
            
                        Assert.IsTrue(response.IsValid, "###Error : " + response.Code + " : " + (response.Fault == null ? string.Empty : response.Fault.Message + " : " + response.Fault.Reason));

            var createdEntity = response.Message;

            foreach (var identifier in mappings)
            {
                var mappingResponse = mdmService.CreateMapping(createdEntity.ToMdmKey(), identifier);
                Assert.IsTrue(mappingResponse.IsValid);
                createdEntity.Identifiers.Add(identifier);
            }

            return createdEntity;
        }

        protected static void SetAdditionalData(Broker entity)
        {
			
            var party = PartyData.PostBasicEntity();
            entity.Party = party.ToMdmId().ToEntityId();
	
        }
    }
}
