// This code was generated by a tool: ViewModelTemplates\EntitySelectorViewModelTemplate.tt
namespace Admin.ExchangeModule.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;

    using Common;
    using Common.Events;
    using Common.Extensions;
    using Common.UI.ViewModels;

    using EnergyTrading;
    using EnergyTrading.Contracts.Search;
    using EnergyTrading.Mdm.Client.Services;
    using EnergyTrading.MDM.Contracts.Sample;
    using EnergyTrading.Search;

    using Microsoft.Practices.Prism.Events;
    using Microsoft.Practices.Prism.Regions;
    using Microsoft.Practices.Prism.ViewModel;

    public class ExchangeSelectorViewModel : NotificationObject
    {
        private readonly IMdmService entityService;

        private readonly IEventAggregator eventAggregator;

        private readonly IRegionManager regionManager;

        private DateTime asOf;

        private string entitySearchText;

        private ObservableCollection<SelectorViewModel> exchanges;

        private SelectorViewModel selectedExchange;

        public ExchangeSelectorViewModel(
            IEventAggregator eventAggregator, 
            IMdmService entityService, 
            IRegionManager regionManager)
        {
            this.eventAggregator = eventAggregator;
            this.entityService = entityService;
            this.regionManager = regionManager;
            this.AsOf = SystemTime.UtcNow().Date;
        }

        public DateTime AsOf
        {
            get
            {
                return this.asOf;
            }

            set
            {
                this.asOf = value;
                this.RaisePropertyChanged(() => this.AsOf);
            }
        }

        public string EntitySearchText
        {
            get
            {
                return this.entitySearchText;
            }

            set
            {
                this.entitySearchText = value;
                this.RaisePropertyChanged(() => this.EntitySearchText);
            }
        }

        public ObservableCollection<SelectorViewModel> Exchanges
        {
            get
            {
                return this.exchanges;
            }

            set
            {
                this.exchanges = value;
                this.RaisePropertyChanged(() => this.Exchanges);
            }
        }

        public SelectorViewModel SelectedExchange
        {
            get
            {
                return this.selectedExchange;
            }

            set
            {
                this.selectedExchange = value;
                this.RaisePropertyChanged(() => this.SelectedExchange);
            }
        }

        public void CancelSelection()
        {
            this.eventAggregator.Publish(new EntitySelectedEvent(string.Empty, 0, string.Empty));
        }

        public void SearchForEntity()
        {
            Search search = SearchBuilder.CreateSearch();
            search.AsOf = this.AsOf;
            search.AddSearchCriteria(SearchCombinator.And)
                .AddCriteria("Name", SearchCondition.Contains, this.EntitySearchText);

            search.SearchOptions.OrderBy = "Name";
            this.entityService.ExecuteAsyncSearch<Exchange>(
                search, 
                response =>
                    {
                        IList<Exchange> searchResults = response;
                        this.Exchanges =
                            new ObservableCollection<SelectorViewModel>(
                                searchResults.Select(x => new SelectorViewModel(x.MdmId().Value, x.Details.Name))
                                    .OrderBy(y => y.Name));
                    }, 
                this.eventAggregator);
        }

        public void SelectExchange()
        {
            var entitySelectionViewContext =
                (EntitySelectionViewContext)this.regionManager.Regions[RegionNames.EntitySelectorRegion].Context;
            this.eventAggregator.Publish(
                new EntitySelectedEvent(
                    entitySelectionViewContext.SelectedPropertyName, 
                    this.SelectedExchange.Id, 
                    this.SelectedExchange.Name));
        }
    }
}