// This code was generated by a tool: ViewModelTemplates\EntityViewModelTemplate.tt
namespace Admin.ExchangeModule.ViewModels
{
    using System;
    using System.Linq.Expressions;

    using Common.Events;
    using Common.Extensions;
    using Common.Framework;
    using Common.Services;

    using EnergyTrading.Mdm.Contracts;
    using EnergyTrading.MDM.Contracts.Sample;

    using Microsoft.Practices.Prism.Events;
    using Microsoft.Practices.Prism.ViewModel;

    public class ExchangeViewModel : NotificationObject
    {
        private readonly IEventAggregator eventAggregator;

        private readonly Exchange exchange;

        private bool canSave;

        private DateTime end;

        private string fax;

        private string name;

        private int? partyId;

        private string partyName;

        private string phone;

        private DateTime start;

        public ExchangeViewModel(IEventAggregator eventAggregator)
        {
            this.eventAggregator = eventAggregator;

            this.exchange = new Exchange
                                {
                                    MdmSystemData =
                                        new SystemData
                                            {
                                                StartDate = DateUtility.MinDate, 
                                                EndDate = DateUtility.MaxDate
                                            }
                                };

            this.Start = this.exchange.MdmSystemData.StartDate.Value;

            this.End = this.exchange.MdmSystemData.EndDate.Value;
        }

        public ExchangeViewModel(EntityWithETag<Exchange> ewe, IEventAggregator eventAggregator)
        {
            this.eventAggregator = eventAggregator;
            this.exchange = ewe.Object;

            this.Id = this.exchange.MdmId();
            this.ETag = ewe.ETag;

            if (this.exchange.MdmSystemData != null && this.exchange.MdmSystemData.StartDate != null)
            {
                this.Start = this.exchange.MdmSystemData.StartDate.Value;
            }

            if (this.exchange.MdmSystemData != null && this.exchange.MdmSystemData.EndDate != null)
            {
                this.End = this.exchange.MdmSystemData.EndDate.Value;
            }

            this.Name = this.exchange.Details.Name;

            this.Phone = this.exchange.Details.Phone;

            this.Fax = this.exchange.Details.Fax;

            this.PartyId = this.exchange.Party.MdmId();

            this.PartyName = this.exchange.Party != null ? this.exchange.Party.Name : null;
        }

        public bool CanSave
        {
            get
            {
                return this.canSave;
            }

            set
            {
                this.canSave = value;
                this.RaisePropertyChanged(() => this.CanSave);
            }
        }

        public string ETag { get; private set; }

        public DateTime End
        {
            get
            {
                return this.end;
            }

            set
            {
                this.ChangeProperty(() => this.End, ref this.end, value);
            }
        }

        public string Fax
        {
            get
            {
                return this.fax;
            }

            set
            {
                this.ChangeProperty(() => this.Fax, ref this.fax, value);
            }
        }

        public int? Id { get; private set; }

        public string Name
        {
            get
            {
                return this.name;
            }

            set
            {
                this.ChangeProperty(() => this.Name, ref this.name, value);
            }
        }

        public int? PartyId
        {
            get
            {
                return this.partyId;
            }

            set
            {
                this.ChangeProperty(() => this.PartyId, ref this.partyId, value);
            }
        }

        public string PartyName
        {
            get
            {
                return this.partyName;
            }

            set
            {
                this.partyName = value;
                this.RaisePropertyChanged(() => this.PartyName);
            }
        }

        public string Phone
        {
            get
            {
                return this.phone;
            }

            set
            {
                this.ChangeProperty(() => this.Phone, ref this.phone, value);
            }
        }

        public DateTime Start
        {
            get
            {
                return this.start;
            }

            set
            {
                this.ChangeProperty(() => this.Start, ref this.start, value);
            }
        }

        public Exchange Model()
        {
            return new Exchange
                       {
                           Details = new ExchangeDetails { Name = this.Name, Phone = this.Phone, Fax = this.Fax }, 
                           MdmSystemData = new SystemData { StartDate = this.Start, EndDate = this.End }, 
                           Party =
                               this.PartyId == null
                                   ? null
                                   : new EntityId
                                         {
                                             Identifier =
                                                 new MdmId
                                                     {
                                                         IsMdmId = true, 
                                                         Identifier = this.PartyId.ToString()
                                                     }
                                         }
                       };
        }

        private void ChangeProperty<T>(Expression<Func<T>> property, ref T variable, T newValue)
        {
            variable = newValue;
            this.RaisePropertyChanged(property);
            this.CanSave = this.HasChanges();
            this.eventAggregator.Publish(new CanSaveEvent(this.CanSave));
        }

        private bool HasChanges()
        {
            return
                !(this.exchange.MdmSystemData.StartDate == this.Start && this.exchange.MdmSystemData.EndDate == this.End
                  && this.exchange.Details.Name == this.Name && this.exchange.Details.Phone == this.Phone
                  && this.exchange.Details.Fax == this.Fax && this.PartyHasNoChanges());
        }

        private bool PartyHasNoChanges()
        {
            int? id;
            if (this.exchange.Party == null)
            {
                id = null;
            }
            else
            {
                id = this.exchange.Party.Identifier.Identifier.ParseToNullableInt();
            }

            return id == this.partyId;
        }
    }
}