// This code was generated by a tool: ViewTemplates\EntityEmbeddedSearchResultsViewCodeTemplate.tt
namespace Admin.BrokerModule.Views
{
    using System.Windows.Controls;

    using Admin.BrokerModule.ViewModels;

    /// <summary>
    /// Interaction logic for BrokerEmbeddedSearchResultsView.xaml
    /// </summary>
    public partial class BrokerEmbeddedSearchResultsView : UserControl
    {
        public BrokerEmbeddedSearchResultsView(
            BrokerEmbeddedSearchResultsViewModel brokerEmbeddedSearchResultsViewModel)
        {
            this.DataContext = brokerEmbeddedSearchResultsViewModel;
            this.InitializeComponent();
        }
    }
}