// This code was generated by a tool: InfrastructureTemplates\EntityViewNamesTemplate.tt
namespace Admin.PersonModule.Views
{
    public static class PersonViewNames
    {
        public static string PersonAddView = "PersonAddView";

        public static string PersonEditView = "PersonEditView";

        public static string PersonEmbeddedSearchResultsView = "PersonEmbeddedSearchResultsView";

        public static string PersonSearchResultsView = "Person";
    }
}