// This code was generated by a tool: InfrastructureTemplates\EntityViewNamesTemplate.tt
namespace Admin.LegalEntityModule.Views
{
    public static class LegalEntityViewNames
    {
        public static string LegalEntityAddView = "LegalEntityAddView";

        public static string LegalEntityEditView = "LegalEntityEditView";

        public static string LegalEntityEmbeddedSearchResultsView = "LegalEntityEmbeddedSearchResultsView";

        public static string LegalEntitySearchResultsView = "LegalEntity";
    }
}