// This code was generated by a tool: ViewTemplates\EntityAddViewCodeTemplate.tt
namespace Admin.LegalEntityModule.Views
{
    using System.Windows.Controls;
    using Admin.LegalEntityModule.ViewModels;

    /// <summary>
    /// Interaction logic for LegalEntityAddView.xaml
    /// </summary>
    public partial class LegalEntityAddView : UserControl
    {
        public LegalEntityAddView(LegalEntityAddViewModel legalentityAddViewModel)
        {
            this.DataContext = legalentityAddViewModel;
            this.InitializeComponent();
        }
    }
}
