// This code was generated by a tool: ViewTemplates\EntityEditViewCodeTemplate.tt
namespace Admin.LegalEntityModule.Views
{
    using System.Windows.Controls;
    using Admin.LegalEntityModule.ViewModels;

    /// <summary>
    /// Interaction logic for LegalEntityEditView.xaml
    /// </summary>
    public partial class LegalEntityEditView : UserControl
    {
        public LegalEntityEditView(LegalEntityEditViewModel legalentityEditViewModel)
        {
            this.DataContext = legalentityEditViewModel;
            this.InitializeComponent();
        }
    }
}
