// This code was generated by a tool: InfrastructureTemplates\EntityViewNamesTemplate.tt
namespace Admin.LocationModule.Views
{
    public static class LocationViewNames
    {
        public static string LocationAddCloneView = "LocationAddCloneView";

        public static string LocationAddView = "LocationAddView";

        public static string LocationEditCloneView = "LocationEditCloneView";

        public static string LocationEditView = "LocationEditView";

        public static string LocationEmbeddedSearchResultsView = "LocationEmbeddedSearchResultsView";

        public static string LocationSearchResultsView = "Location";
    }
}