// This code was generated by a tool: ViewTemplates\EntityEmbeddedSearchResultsViewCodeTemplate.tt
namespace Admin.LocationModule.Views
{
    using System.Windows.Controls;

    using Admin.LocationModule.ViewModels;

    /// <summary>
    /// Interaction logic for LocationEmbeddedSearchResultsView.xaml
    /// </summary>
    public partial class LocationEmbeddedSearchResultsView : UserControl
    {
        public LocationEmbeddedSearchResultsView(
            LocationEmbeddedSearchResultsViewModel locationEmbeddedSearchResultsViewModel)
        {
            this.DataContext = locationEmbeddedSearchResultsViewModel;
            this.InitializeComponent();
        }
    }
}