// This code was generated by a tool: ViewModelTemplates\EntitySearchResultsViewModelTemplate.tt
namespace Admin.ExchangeModule.ViewModels
{
	using System.Windows;
	using System.Windows.Media;

    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Windows.Input;

    using Admin.ExchangeModule.Uris;
    using Admin.ExchangeModule.Views;

    using Common.Events;
    using Common.Extensions;
    using Common.Services;

    using Microsoft.Practices.Prism;
    using Microsoft.Practices.Prism.Events;
    using Microsoft.Practices.Prism.ViewModel;

    using EnergyTrading.Contracts.Search;
    using EnergyTrading.Mdm.Client.Services;
    using EnergyTrading.MDM.Contracts.Sample; using EnergyTrading.Mdm.Contracts;

    public class ExchangeSearchResultsViewModel : NotificationObject, IActiveAware
    {
        private readonly IMdmService entityService;
        private readonly IEventAggregator eventAggregator;
        private readonly INavigationService navigationService;
        private bool isActive;

        private ObservableCollection<ExchangeViewModel> exchanges;

        private Search search;
        private ExchangeViewModel selectedExchange;

        public ExchangeSearchResultsViewModel(
            INavigationService navigationService, 
            IEventAggregator eventAggregator, 
            IMdmService entityService)
        {
            this.navigationService = navigationService;
            this.eventAggregator = eventAggregator;
            this.entityService = entityService;
            this.IsActiveChanged += this.OnIsActiveChanged;
        }

        public event EventHandler IsActiveChanged;

        public bool IsActive
        {
            get
            {
                return this.isActive;
            }

            set
            {
                if (this.isActive != value)
                {
                    this.isActive = value;
                }

                this.IsActiveChanged(this, EventArgs.Empty);
            }
        }

        public ObservableCollection<ExchangeViewModel> Exchanges
        {
            get
            {
                return this.exchanges;
            }

            set
            {
                this.exchanges = value;
                this.RaisePropertyChanged(() => this.Exchanges);
                if (Exchanges != null && Exchanges.Count > 0 && SelectedExchange == null) SelectedExchange = Exchanges[0];            }
        }

        public ExchangeViewModel SelectedExchange
        {
            get
            {
                return this.selectedExchange;
            }

            set
            {
                this.selectedExchange = value;
                this.RaisePropertyChanged(() => this.SelectedExchange);
            }
        }
        
        public void NavigateToDetail(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Enter && this.SelectedExchange != null)
            {
                this.navigationService.NavigateMain(new ExchangeEditUri(this.SelectedExchange.Id.Value, this.search.AsOf.Value));
            }
        }

        public void NavigateToDetailDoubleClick(object sender, MouseButtonEventArgs e)
        {
			DependencyObject src = VisualTreeHelper.GetParent((DependencyObject)e.OriginalSource);

		    if (src.GetType() == typeof(System.Windows.Controls.ContentPresenter))
		    {
	            if (this.SelectedExchange != null)
	            {
	                this.navigationService.NavigateMain(new ExchangeEditUri(this.SelectedExchange.Id.Value, this.search.AsOf.Value));
	            }
		    }
        }

        public void Sorting()
        {
            this.SelectedExchange = null;
        }

        private void OnIsActiveChanged(object sender, EventArgs eventArgs)
        {
            if (this.isActive)
            {
                this.eventAggregator.Subscribe<SearchRequestEvent>(this.SearchRequest);
                return;
            }

            this.eventAggregator.Unsubscribe<SearchRequestEvent>(this.SearchRequest);
        }

        private void SearchRequest(SearchRequestEvent searchRequestEvent)
        {
            searchRequestEvent.Search.SearchOptions.OrderBy = "Name";

            this.entityService.ExecuteAsyncSearch<Exchange>(
                this.search = searchRequestEvent.Search, 
                (response) =>
                    {
                        IList<Exchange> searchResults = response;
                        this.Exchanges =
                            new ObservableCollection<ExchangeViewModel>(
                                searchResults.Select(
                                    x =>
                                    new ExchangeViewModel(new EntityWithETag<Exchange>(x, null), this.eventAggregator)).OrderBy(y => y.Name));
                    }, 
                this.eventAggregator);
        }
    }
}
