// This code was generated by a tool: ViewTemplates\EntitySelectorViewCodeTemplate.tt
namespace Admin.ExchangeModule.Views
{
    using System.Windows;
    using System.Windows.Controls;
    using System.Windows.Input;

    using Admin.ExchangeModule.ViewModels;

    /// <summary>
    /// Interaction logic for ExchangeSelectorView.xaml
    /// </summary>
    public partial class ExchangeSelectorView : UserControl
    {
        public ExchangeSelectorView(ExchangeSelectorViewModel exchangeSelectorViewModel)
        {
            this.DataContext = exchangeSelectorViewModel;
            this.InitializeComponent();
            this.Loaded += OnLoaded;
        }

        public void SelectExchangeMDC(object sender, MouseButtonEventArgs e)
        {
            ((ExchangeSelectorViewModel)DataContext).SelectExchange();
        }

        private void OnLoaded(object sender, RoutedEventArgs e)
        {
            Keyboard.Focus(SearchCriteriaTextBox);
        }
    }
}