// This code was generated by a tool: ViewTemplates\EntitySearchResultsViewCodeTemplate.tt
namespace Admin.ExchangeModule.Views
{
    using System.Windows.Controls;

    using Admin.ExchangeModule.ViewModels;

    /// <summary>
    /// Interaction logic for ExchangeSearchResultsView.xaml
    /// </summary>
    public partial class ExchangeSearchResultsView : UserControl
    {
        public ExchangeSearchResultsView(ExchangeSearchResultsViewModel exchangeSearchResultsViewModel)
        {
            this.DataContext = exchangeSearchResultsViewModel;
            this.InitializeComponent();
        }
    }
}