// This code was generated by a tool: ViewTemplates\EntityEmbeddedSearchResultsViewCodeTemplate.tt
namespace Admin.ExchangeModule.Views
{
    using System.Windows.Controls;
    using Admin.ExchangeModule.ViewModels;

    /// <summary>
    /// Interaction logic for ExchangeEmbeddedSearchResultsView.xaml
    /// </summary>
    public partial class ExchangeEmbeddedSearchResultsView : UserControl
    {
        public ExchangeEmbeddedSearchResultsView(ExchangeEmbeddedSearchResultsViewModel exchangeEmbeddedSearchResultsViewModel)
        {
            this.DataContext = exchangeEmbeddedSearchResultsViewModel;
            this.InitializeComponent();
        }
    }
}
