// This code was generated by a tool: ViewTemplates\EntityEditViewCodeTemplate.tt
namespace Admin.PersonModule.Views
{
    using System.Windows.Controls;
    using Admin.PersonModule.ViewModels;

    /// <summary>
    /// Interaction logic for PersonEditView.xaml
    /// </summary>
    public partial class PersonEditView : UserControl
    {
        public PersonEditView(PersonEditViewModel personEditViewModel)
        {
            this.DataContext = personEditViewModel;
            this.InitializeComponent();
        }
    }
}
