// This code was generated by a tool: ViewTemplates\EntityEmbeddedSearchResultsViewCodeTemplate.tt
namespace Admin.PersonModule.Views
{
    using System.Windows.Controls;

    using Admin.PersonModule.ViewModels;

    /// <summary>
    /// Interaction logic for PersonEmbeddedSearchResultsView.xaml
    /// </summary>
    public partial class PersonEmbeddedSearchResultsView : UserControl
    {
        public PersonEmbeddedSearchResultsView(
            PersonEmbeddedSearchResultsViewModel personEmbeddedSearchResultsViewModel)
        {
            this.DataContext = personEmbeddedSearchResultsViewModel;
            this.InitializeComponent();
        }
    }
}