// This code was generated by a tool: ViewTemplates\EntitySearchResultsViewCodeTemplate.tt
namespace Admin.PersonModule.Views
{
    using System.Windows.Controls;
    using Admin.PersonModule.ViewModels;

    /// <summary>
    /// Interaction logic for PersonSearchResultsView.xaml
    /// </summary>
    public partial class PersonSearchResultsView : UserControl
    {
        public PersonSearchResultsView(PersonSearchResultsViewModel personSearchResultsViewModel)
        {
            this.DataContext = personSearchResultsViewModel;
            this.InitializeComponent();
        }
    }
}
