// This code was generated by a tool: ViewTemplates\EntityAddViewCodeTemplate.tt
namespace Admin.PartyRoleModule.Views
{
    using System.Windows.Controls;

    using Admin.PartyRoleModule.ViewModels;

    /// <summary>
    /// Interaction logic for PartyRoleAddView.xaml
    /// </summary>
    public partial class PartyRoleAddView : UserControl
    {
        public PartyRoleAddView(PartyRoleAddViewModel partyroleAddViewModel)
        {
            this.DataContext = partyroleAddViewModel;
            this.InitializeComponent();
        }
    }
}