// This code was generated by a tool: ViewModelTemplates\EntityEmbeddedSearchResultsViewModelTemplate.tt
namespace Admin.SourceSystemModule.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Windows.Input;

    using Admin.SourceSystemModule.Uris;

    using Common.Extensions;
    using Common.Services;

    using EnergyTrading.Contracts.Search;
    using EnergyTrading.Mdm.Client.Services;
    using EnergyTrading.Mdm.Contracts;
    using EnergyTrading.Search;

    using Microsoft.Practices.Prism;
    using Microsoft.Practices.Prism.Events;
    using Microsoft.Practices.Prism.Regions;
    using Microsoft.Practices.Prism.ViewModel;

    public class SourceSystemEmbeddedSearchResultsViewModel : NotificationObject, IActiveAware
    {
        private readonly IMdmService entityService;

        private readonly IEventAggregator eventAggregator;

        private readonly INavigationService navigationService;

        private readonly IRegionManager regionManager;

        private bool isActive;

        private Search search;

        private SourceSystemViewModel selectedSourceSystem;

        private ObservableCollection<SourceSystemViewModel> sourcesystems;

        public SourceSystemEmbeddedSearchResultsViewModel(
            INavigationService navigationService, 
            IEventAggregator eventAggregator, 
            IMdmService entityService, 
            IRegionManager regionManager)
        {
            this.navigationService = navigationService;
            this.eventAggregator = eventAggregator;
            this.entityService = entityService;
            this.regionManager = regionManager;
            this.IsActiveChanged += this.OnIsActiveChanged;
        }

        public event EventHandler IsActiveChanged;

        public bool IsActive
        {
            get
            {
                return this.isActive;
            }

            set
            {
                if (this.isActive != value)
                {
                    this.isActive = value;
                }

                this.IsActiveChanged(this, EventArgs.Empty);
            }
        }

        public SourceSystemViewModel SelectedSourceSystem
        {
            get
            {
                return this.selectedSourceSystem;
            }

            set
            {
                this.selectedSourceSystem = value;
                this.RaisePropertyChanged(() => this.SelectedSourceSystem);
            }
        }

        public ObservableCollection<SourceSystemViewModel> SourceSystems
        {
            get
            {
                return this.sourcesystems;
            }

            set
            {
                this.sourcesystems = value;
                this.RaisePropertyChanged(() => this.SourceSystems);
                if (SourceSystems != null && SourceSystems.Count > 0 && SelectedSourceSystem == null)
                {
                    SelectedSourceSystem = SourceSystems[0];
                }
            }
        }

        public void NavigateToDetail(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Enter && this.SelectedSourceSystem != null)
            {
                this.navigationService.NavigateMain(
                    new SourceSystemEditUri(this.SelectedSourceSystem.Id.Value, this.search.AsOf.Value));
            }
        }

        public void NavigateToDetailDoubleClick()
        {
            if (this.SelectedSourceSystem != null)
            {
                this.navigationService.NavigateMain(
                    new SourceSystemEditUri(this.SelectedSourceSystem.Id.Value, this.search.AsOf.Value));
            }
        }

        public void Sorting()
        {
            this.SelectedSourceSystem = null;
        }

        private IRegion MyRegion(IRegionCollection regions)
        {
            for (int i = regions.Count() - 1; i >= 0; i--)
            {
                if (regions.ElementAt(i).Name.EndsWith("-SourceSystemSearchResultsRegion")
                    && regions.ElementAt(i).Context != null)
                {
                    return regions.ElementAt(i);
                }
            }

            return null;
        }

        private void OnIsActiveChanged(object sender, EventArgs eventArgs)
        {
            if (this.isActive)
            {
                Search search = SearchBuilder.CreateSearch();

                var context = MyRegion(this.regionManager.Regions).Context as Tuple<int, DateTime?, string>;
                search.AsOf = context.Item2;

                string field;
                switch (context.Item3)
                {
                    case "SourceSystem":
                        field = "Parent.Id";
                        break;
                    default:
                        field = context.Item3 + ".Id";
                        break;
                }

                if (field.Contains("|"))
                {
                    search.SearchFields.Combinator = SearchCombinator.Or;
                    var fields = field.Split(new[] { '|' });

                    foreach (string f in fields)
                    {
                        search.AddSearchCriteria(SearchCombinator.And)
                            .AddCriteria(f, SearchCondition.NumericEquals, context.Item1.ToString());
                    }
                }
                else
                {
                    search.AddSearchCriteria(SearchCombinator.And)
                        .AddCriteria(field, SearchCondition.NumericEquals, context.Item1.ToString());
                }

                this.entityService.ExecuteAsyncSearch<SourceSystem>(
                    this.search = search, 
                    response =>
                        {
                            IList<SourceSystem> searchResults = response;
                            this.SourceSystems =
                                new ObservableCollection<SourceSystemViewModel>(
                                    searchResults.Select(
                                        x =>
                                        new SourceSystemViewModel(
                                            new EntityWithETag<SourceSystem>(x, null), 
                                            this.eventAggregator)).OrderBy(y => y.Name));
                        }, 
                    this.eventAggregator, 
                    false);
                return;
            }

            this.SourceSystems = new ObservableCollection<SourceSystemViewModel>();
        }
    }
}