// This code was generated by a tool: ViewTemplates\EntitySelectorViewCodeTemplate.tt

using System.Windows;
using System.Windows.Input;

namespace Admin.PartyAccountabilityModule.Views
{
    using System.Windows.Controls;
    using Admin.PartyAccountabilityModule.ViewModels;

    /// <summary>
    /// Interaction logic for PartyAccountabilitySelectorView.xaml
    /// </summary>
    public partial class PartyAccountabilitySelectorView : UserControl
    {
        public PartyAccountabilitySelectorView(PartyAccountabilitySelectorViewModel partyaccountabilitySelectorViewModel)
        {
            this.DataContext = partyaccountabilitySelectorViewModel;
            this.InitializeComponent();
            this.Loaded += OnLoaded;
        }

        public void SelectPartyAccountabilityMDC(object sender, MouseButtonEventArgs e)
        {
            ((PartyAccountabilitySelectorViewModel)DataContext).SelectPartyAccountability();
        }

        private void OnLoaded(object sender, RoutedEventArgs e)
        {
            Keyboard.Focus(SearchCriteriaTextBox);
        }
    }
}
