// This code was generated by a tool: ViewModelTemplates\EntityViewModelTemplate.tt
namespace Admin.PartyAccountabilityModule.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;

    using Common.Events;
    using Common.Extensions;
    using Common.Framework;
    using Common.Services;

    using Microsoft.Practices.Prism.Events;
    using Microsoft.Practices.Prism.ViewModel;

    using EnergyTrading.MDM.Contracts.Sample; using EnergyTrading.Mdm.Contracts;

    public class PartyAccountabilityViewModel : NotificationObject
    {
        private readonly IEventAggregator eventAggregator;
        private readonly PartyAccountability partyaccountability;
        private bool canSave;

        private DateTime end;

        private DateTime start;

        public PartyAccountabilityViewModel(IEventAggregator eventAggregator)
        {
            this.eventAggregator = eventAggregator;

            this.partyaccountability = new PartyAccountability
            {
                MdmSystemData = new SystemData { StartDate = DateUtility.MinDate, EndDate = DateUtility.MaxDate } 
            };

            this.Start = this.partyaccountability.MdmSystemData.StartDate.Value;

            this.End = this.partyaccountability.MdmSystemData.EndDate.Value;
        }

        public PartyAccountabilityViewModel(EntityWithETag<PartyAccountability> ewe, IEventAggregator eventAggregator)
        {
            this.eventAggregator = eventAggregator;
            this.partyaccountability = ewe.Object;

            this.Id = this.partyaccountability.MdmId();
            this.ETag = ewe.ETag;

            if (this.partyaccountability.MdmSystemData != null && this.partyaccountability.MdmSystemData.StartDate != null)
            {
                this.Start = this.partyaccountability.MdmSystemData.StartDate.Value;
            }

            if (this.partyaccountability.MdmSystemData != null && this.partyaccountability.MdmSystemData.EndDate != null)
            {
                this.End = this.partyaccountability.MdmSystemData.EndDate.Value;
            }

            this.Name = this.partyaccountability.Details.Name;

            this.SourcePartyId = this.partyaccountability.Details.SourceParty.MdmId();

            this.SourcePartyName = this.partyaccountability.Details.SourceParty != null ? this.partyaccountability.Details.SourceParty.Name : null;

            this.TargetPartyId = this.partyaccountability.Details.TargetParty.MdmId();

            this.TargetPartyName = this.partyaccountability.Details.TargetParty != null ? this.partyaccountability.Details.TargetParty.Name : null;

            this.SourcePersonId = this.partyaccountability.Details.SourcePerson.MdmId();

            this.SourcePersonName = this.partyaccountability.Details.SourcePerson != null ? this.partyaccountability.Details.SourcePerson.Name : null;

            this.TargetPersonId = this.partyaccountability.Details.TargetPerson.MdmId();

            this.TargetPersonName = this.partyaccountability.Details.TargetPerson != null ? this.partyaccountability.Details.TargetPerson.Name : null;

            this.PartyAccountabilityType = this.partyaccountability.Details.PartyAccountabilityType;
        }

        private System.String name;
        public System.String Name 
        { 
            get { return this.name; }
            set { this.ChangeProperty(() => this.Name, ref this.name, value); }
        }

        private int? sourcepartyId;
        public int? SourcePartyId 
        {
            get { return this.sourcepartyId; }
            set { this.ChangeProperty(() => this.SourcePartyId, ref this.sourcepartyId, value); }
        }

        private string sourcepartyName;
        public string SourcePartyName 
        {
            get { return this.sourcepartyName; }
            set { this.sourcepartyName = value; this.RaisePropertyChanged(() => this.SourcePartyName); }
        }

        private int? targetpartyId;
        public int? TargetPartyId 
        {
            get { return this.targetpartyId; }
            set { this.ChangeProperty(() => this.TargetPartyId, ref this.targetpartyId, value); }
        }

        private string targetpartyName;
        public string TargetPartyName 
        {
            get { return this.targetpartyName; }
            set { this.targetpartyName = value; this.RaisePropertyChanged(() => this.TargetPartyName); }
        }

        private int? sourcepersonId;
        public int? SourcePersonId 
        {
            get { return this.sourcepersonId; }
            set { this.ChangeProperty(() => this.SourcePersonId, ref this.sourcepersonId, value); }
        }

        private string sourcepersonName;
        public string SourcePersonName 
        {
            get { return this.sourcepersonName; }
            set { this.sourcepersonName = value; this.RaisePropertyChanged(() => this.SourcePersonName); }
        }

        private int? targetpersonId;
        public int? TargetPersonId 
        {
            get { return this.targetpersonId; }
            set { this.ChangeProperty(() => this.TargetPersonId, ref this.targetpersonId, value); }
        }

        private string targetpersonName;
        public string TargetPersonName 
        {
            get { return this.targetpersonName; }
            set { this.targetpersonName = value; this.RaisePropertyChanged(() => this.TargetPersonName); }
        }

        private System.String partyaccountabilitytype;
        public System.String PartyAccountabilityType 
        { 
            get { return this.partyaccountabilitytype; }
            set { this.ChangeProperty(() => this.PartyAccountabilityType, ref this.partyaccountabilitytype, value); }
        }

        public bool CanSave
        {
            get
            {
                return this.canSave;
            }
            set
            {
                this.canSave = value;
                this.RaisePropertyChanged(() => this.CanSave);
            }
        }

        public string ETag { get; private set; }

        public DateTime End
        {
            get
            {
                return this.end;
            }
            set
            {
                this.ChangeProperty(() => this.End, ref this.end, value);
            }
        }

        public int? Id { get; private set; }

        public DateTime Start
        {
            get
            {
                return this.start;
            }
            set
            {
                this.ChangeProperty(() => this.Start, ref this.start, value);
            }
        }

        public PartyAccountability Model()
        {
            return new PartyAccountability
            {
                Details = new PartyAccountabilityDetails 
                {
                    Name = this.Name
                    ,SourceParty = this.SourcePartyId == null ? null :
                        new EntityId { Identifier = new MdmId { IsMdmId = true, Identifier = this.SourcePartyId.ToString() } }
                    ,TargetParty = this.TargetPartyId == null ? null :
                        new EntityId { Identifier = new MdmId { IsMdmId = true, Identifier = this.TargetPartyId.ToString() } }
                    ,SourcePerson = this.SourcePersonId == null ? null :
                        new EntityId { Identifier = new MdmId { IsMdmId = true, Identifier = this.SourcePersonId.ToString() } }
                    ,TargetPerson = this.TargetPersonId == null ? null :
                        new EntityId { Identifier = new MdmId { IsMdmId = true, Identifier = this.TargetPersonId.ToString() } }
                    ,PartyAccountabilityType = this.PartyAccountabilityType
                }, 
                MdmSystemData = new SystemData { StartDate = this.Start, EndDate = this.End }
            };
        }

        private void ChangeProperty<T>(Expression<Func<T>> property, ref T variable, T newValue)
        {
            variable = newValue;
            this.RaisePropertyChanged(property);
            this.CanSave = this.HasChanges();
            this.eventAggregator.Publish(new CanSaveEvent(this.CanSave));
        }

        private bool HasChanges()
        {
            return
                !(
                    this.partyaccountability.MdmSystemData.StartDate == this.Start 
                    && this.partyaccountability.MdmSystemData.EndDate == this.End
                    && this.partyaccountability.Details.Name == this.Name 
                    && this.SourcePartyHasNoChanges()
                    && this.TargetPartyHasNoChanges()
                    && this.SourcePersonHasNoChanges()
                    && this.TargetPersonHasNoChanges()
                    && this.partyaccountability.Details.PartyAccountabilityType == this.PartyAccountabilityType 
                );
        }

        private bool SourcePartyHasNoChanges()
        {
            int? id;
            if (this.partyaccountability.Details.SourceParty == null)
            {
                id = null;
            }
            else
            {
                id = this.partyaccountability.Details.SourceParty.Identifier.Identifier.ParseToNullableInt();
            }

            return id == this.sourcepartyId;
        }

        private bool TargetPartyHasNoChanges()
        {
            int? id;
            if (this.partyaccountability.Details.TargetParty == null)
            {
                id = null;
            }
            else
            {
                id = this.partyaccountability.Details.TargetParty.Identifier.Identifier.ParseToNullableInt();
            }

            return id == this.targetpartyId;
        }

        private bool SourcePersonHasNoChanges()
        {
            int? id;
            if (this.partyaccountability.Details.SourcePerson == null)
            {
                id = null;
            }
            else
            {
                id = this.partyaccountability.Details.SourcePerson.Identifier.Identifier.ParseToNullableInt();
            }

            return id == this.sourcepersonId;
        }

        private bool TargetPersonHasNoChanges()
        {
            int? id;
            if (this.partyaccountability.Details.TargetPerson == null)
            {
                id = null;
            }
            else
            {
                id = this.partyaccountability.Details.TargetPerson.Identifier.Identifier.ParseToNullableInt();
            }

            return id == this.targetpersonId;
        }
    }
}
