// This code was generated by a tool: ViewModelTemplates\EntityAddCloneViewModelTemplate.tt
namespace Admin.LocationModule.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using Uris;

    using Common;
    using Common.Events;
    using Common.Extensions;
    using Common.Services;
    using Common.UI;

    using Microsoft.Practices.Prism.Events;
    using Microsoft.Practices.Prism.Interactivity.InteractionRequest;
    using Microsoft.Practices.Prism.Regions;
    using Microsoft.Practices.Prism.ViewModel;

    using EnergyTrading.Mdm.Client.Services;
    using EnergyTrading;
    using EnergyTrading.MDM.Contracts.Sample; using EnergyTrading.Mdm.Contracts;

    public class LocationAddCloneViewModel : NotificationObject, INavigationAware, IConfirmNavigationRequest
    {
        private readonly InteractionRequest<Confirmation> confirmationFromViewModelInteractionRequest;
        private readonly IMdmService entityService;
        private readonly INavigationService navigationService;
        private readonly IEventAggregator eventAggregator;

        private LocationViewModel location;

        public LocationAddCloneViewModel(IEventAggregator eventAggregator, IMdmService entityService, INavigationService navigationService           ,IList<string> typeConfiguration)
        {
            this.eventAggregator = eventAggregator;
            this.confirmationFromViewModelInteractionRequest = new InteractionRequest<Confirmation>();
            this.entityService = entityService;
            this.navigationService = navigationService;
            this.Location = new LocationViewModel(this.eventAggregator);            
                         this.TypeConfiguration = typeConfiguration;
                   }

        /// <summary>
        /// Gets the notification from view model interaction request. View binds to this property
        /// </summary>
        public IInteractionRequest ConfirmationFromViewModelInteractionRequest
        {
            get
            {
                return this.confirmationFromViewModelInteractionRequest;
            }
        }

        public LocationViewModel Location
        {
            get
            {
                return this.location;
            }

            set
            {
                this.location = value;
                this.RaisePropertyChanged(() => this.Location);
            }
        }
        
        
        public void SelectParent()
        {
            this.eventAggregator.Publish(new EntitySelectEvent("Location","Parent"));
        }
        
        public void DeleteParent()
        {
            this.Location.ParentId = null;
            this.Location.ParentName = string.Empty;
        }
        
                public IList<string> TypeConfiguration
        {
            get;
            set;
        }
           
        public void ConfirmNavigationRequest(NavigationContext navigationContext, Action<bool> continuationCallback)
        {
            if (this.Location.CanSave)
            {
                this.eventAggregator.Publish(new DialogOpenEvent(true));
                this.confirmationFromViewModelInteractionRequest.Raise(
                    new Confirmation { Content = Message.UnsavedChanges, Title = Message.UnsavedChangeTitle },
                    confirmation =>
                        {
                            continuationCallback(confirmation.Confirmed);
                            this.eventAggregator.Publish(new DialogOpenEvent(false));
                        });
            }
            else
            {
                continuationCallback(true);
            }
        }

        public bool IsNavigationTarget(NavigationContext navigationContext)
        {
            return true;
        }

        public void OnNavigatedFrom(NavigationContext navigationContext)
        {
            this.eventAggregator.Unsubscribe<SaveEvent>(this.Save);
            this.eventAggregator.Unsubscribe<EntitySelectedEvent>(this.EntitySelected);
        }

        public void OnNavigatedTo(NavigationContext navigationContext)
        {
            this.eventAggregator.Subscribe<SaveEvent>(this.Save);
            this.eventAggregator.Subscribe<EntitySelectedEvent>(this.EntitySelected);

            int idParam = int.Parse(navigationContext.Parameters[NavigationParameters.EntityId]);

            var validAtString = DateTime.Parse(navigationContext.Parameters[NavigationParameters.ValidAtDate]);
            this.LoadLocationFromService(idParam, validAtString);
        }

        private void LoadLocationFromService(int entityId, DateTime validAt)
        {
            this.entityService.ExecuteAsync(
                () => this.entityService.Get<Location>(entityId, validAt),
                (response) =>
                {
                    this.Location =
                        new LocationViewModel(
                            new EntityWithETag<Location>(response.Message, response.Tag),
                            this.eventAggregator);

                    this.RaisePropertyChanged(string.Empty);
                },
                this.eventAggregator);
        }

        private void EntitySelected(EntitySelectedEvent obj)
        {
            switch (obj.EntityKey)
            {
                case "Parent":
                    this.Location.ParentId = obj.Id;
                    this.Location.ParentName = obj.EntityValue;
                    break;
          }
                        }

        private void Save(SaveEvent saveEvent)
        {
            this.entityService.ExecuteAsync(
                            () => this.entityService.Create(this.Location.Model()),
                            response =>
                                {
                                    // clear down view model - this allows us to navigate away
                                    var originalId = this.Location.Id.Value;
                                    var originalStartDate = this.Location.Start;
                                    this.Location = new LocationViewModel(this.eventAggregator);

                                    this.navigationService.NavigateMain(new LocationEditCloneUri(
                                        response.Message.MdmId().Value, 
                                        response.Message.MdmSystemData.StartDate.Value,
                                        originalId, 
                                        originalStartDate));
                                },
                            this.eventAggregator);
        }

        public void StartToday()
        {
            this.Location.Start = SystemTime.UtcNow().Date;
        }

        public void StartMinimum()
        {
            this.Location.Start = DateUtility.MinDate;
        }
    }
}
    