// This code was generated by a tool: ViewTemplates\EntityEditViewCodeTemplate.tt
namespace Admin.LocationModule.Views
{
    using System.Windows.Controls;
    using Admin.LocationModule.ViewModels;

    /// <summary>
    /// Interaction logic for LocationEditView.xaml
    /// </summary>
    public partial class LocationEditView : UserControl
    {
        public LocationEditView(LocationEditViewModel locationEditViewModel)
        {
            this.DataContext = locationEditViewModel;
            this.InitializeComponent();
        }
    }
}
