// This code was generated by a tool: ViewTemplates\EntityEditCloneViewCodeTemplate.tt
namespace Admin.LocationModule.Views
{
    using System.Windows.Controls;
    using Admin.LocationModule.ViewModels;

    /// <summary>
    /// Interaction logic for LocationEditCloneView.xaml
    /// </summary>
    public partial class LocationEditCloneView : UserControl
    {
        public LocationEditCloneView(LocationEditCloneViewModel locationEditCloneViewModel)
        {
            this.DataContext = locationEditCloneViewModel;
            this.InitializeComponent();
        }
    }
}
